version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ig-project
    ports:
      - 5432:5432
    volumes:
      - ig-project:/var/lib/postgresql/data
volumes:
  ig-project:
